name: surpraise_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  faker: ^2.0.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0

dependencies:
  surpraise_backend_dependencies:
    git:
      https://github.com/viniciusamelio/surpraise_backend_dependencies
